# ==================================================
# backend/app/api/v1/router.py
# Router principal de la API v1.
# Registra todos los sub-routers de cada modulo.
# ==================================================

from fastapi import APIRouter
from backend.app.api.v1.endpoints import auth, catalog, tickets, orders, knowledge, chat

# Router principal que agrupa todos los modulos
api_router = APIRouter(prefix="/api/v1")

api_router.include_router(auth.router)        # /api/v1/auth/...
api_router.include_router(catalog.router)     # /api/v1/catalog/...
api_router.include_router(tickets.router)     # /api/v1/tickets/...
api_router.include_router(orders.router)      # /api/v1/orders/...
api_router.include_router(knowledge.router)   # /api/v1/knowledge/...
api_router.include_router(chat.router)        # /api/v1/chat/...
